### ISSUE TITLE
Server doesn't let players join with the mod installed, kicking them with a "Non [a-z0-9/._-] character in path of location:"

### ISSUE THREAD

**Issue by SuperKnux** [Luligabi1/Logicates#4]
Log: https://mclo.gs/YiCBMlY

I know it's this mod that causes the server to do this (Removed the mod and the server allowed joining again), and i have no idea what it could be doing to cause such a thing.

**Comment by Luligabi1** [comment]
`io.netty.handler.codec.DecoderException: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: te:millingcreate:milling/cobblestone'???minecraft:crafting_shapedyttr:crafting`

Looks like a Create milling recipe's id contains invalid characters. Are you modifying/adding some via datapacks? There's nothing on the log suggesting it's Logicates' fault.

**Comment by Luligabi1** [comment]
@SuperKnux a fix for this has been released on CF and Modrinth under the 1.0.2 version tag. if you find further issues on those versions, please open a new issue!
